# Generated by Django 3.2.5 on 2022-05-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mensagem',
            field=models.CharField(max_length=500, verbose_name='mensagem'),
        ),
        migrations.AlterField(
            model_name='message',
            name='token',
            field=models.CharField(max_length=90, verbose_name='token'),
        ),
    ]
